### ISSUE TITLE
Implementing a functionality that detect conversations and display on the screen.

### ISSUE THREAD

**Issue by beyzaaltuntas** [aligungr/Communica-p-tion#6]
User should be able to see translated text that detected and converted from foreign language speechs as subtitle on the screen of mobile phone or AR glasses. Also hearing impaired users should be able to see text that detected and converted from native speechs as subtitle on the screen of mobile phone or AR glasses.

Subissues :
- [ ]  (Semih) As a user, I would like to see the translated text as subtitle on my mobile application. (#12 )
- [ ]  (Ali) As a developer, I would like to implement 'text to speech' component in order to use in the system. (#17 )
- [ ]  (Beyza) As a user, I would like to see overlay of translated text as subtitle on AR. (#11 )
- [ ]  (Semih) As a developer, I would like to recognize language from string. (#19 )
- [ ]  (Semih) As a developer, I would like to implement string to string translate according to given language. (#22 )
